baseURL = "/"
theme = "hugo-book"
title = "Crónica de un Fracaso Anunciado: Mi Lucha con Gemini"
defaultContentLanguage = "es"

[languages]
  [languages.es]
    languageName = "Español"
    title = "Crónica de un Fracaso: Mi Lucha con Gemini"
    weight = 1
